version: '2'
# Docker Compose file for ELK stack

# Build with:
# docker-compose build elk

# Run with:
# docker-compose up
services:
  elk:
    build: .
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
    environment:
      - "ES_CONNECT_RETRY=100"
    networks:
      - elk

  nginx-filebeat:
    build: ./nginx-filebeat/.
    depends_on:
      - "elk"
    networks:
      - elk

  dummy-app:
    build: ./dummy-app/.
    depends_on:
      - "elk"
      - "nginx-filebeat"
    networks:
      - elk

networks:
  elk:
